version: '3'

services:
  client:
    build:
      context: ./delinked-client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://server:5000/api
    depends_on:
      - server
    volumes:
      - ./delinked-client:/app
      - /app/node_modules
      - /app/.next

  server:
    build:
      context: ./delinked-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/delinked
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo
    volumes:
      - ./delinked-server:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: